server:
  servlet:
    context-path: /api

spring:
  application:
    name: merkur-backend
  datasource:
    url: jdbc:postgresql://localhost:5434/ugykezelo_rendszer
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: validate
      
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    
merkur:
  auth:
    jwt:
      secret: LZQerVGAf9ExRwK1DRXibL5VOJMnexDLZWOsGGja6qJf1H3mDaS714dEFESHuF6SLgXx0DsAZNuJhwUiv5YFDfejbpe4SAhfFvlkxdHTqtnh1wbUcrbyI2MTFPAkuzxFG514AbUFITZMMqQhc4L3z13N95EyGu0nND424cNDBs88v3zBcWwI80xo7sRfjXzANR0qU5sTSGGASBKzXDRS1UOpXnFBvCXrUbbHASaCMDcyeiVQnSV5MHF1NOEemAbDig9CMuw6GDsmT2ecgBoY7igx0yRtnMZN4HRUYBqrvB35r4QM6p77fSTsmqVmJPw742jCtSs8SVHIXmP4eOq5j3n1z9GuoQym1q0DQLNsueOOitsc2ncAIdPkfZE8UzfwY4GeaDVticY4DuwgQVlZX5ZMgBCq6v5HhpwwIcfQL8u0mNtyBueLerzsMcjlmL84MedvrrOlXauWunmPaqwZWBH2WbJG6YiQDHk6xLD0QcQpc7v6n6FPcufZCUn63VtGDJVDp40oJVUaZmbnkMi6T5jBgakm3UWBbrLvRwZ5XsaMo9uQNNJNwJjPHbTfoBvOkI6i4nlUO0hLoUiKcrRvqKtNVpdBm0vSiPyEKvmDo7yd5bHnKelPndXV2rj92V8LJlTbqQ1wSjn0iP1EeobAZfWQAIfvOvExDJgCMmumasP8bUn5RNwiXC5BHcWJVtPVmPrg9vg1U01ndcQRF0UEuUWGq9sijsJhhA1HCiwe3dx2vB785K8aKsPsiJFnjQe0nMqTrFfxv3AcRgQsQZCNBmHbAVgVgFSDnWqsJum0Ok98vcHroiC6vnd8dWozRcUGkIumD4ZCh3f79K4Ule0Qa87neCVmXpqL93piRBn6MFI5vMzgOm7JAUhhYVnOgCykTNR3EpwwvusOZ9SVxMvIdBeWzAwo6S5YtycDthkRYiVgSTZAceneGxhya0PCAQ5UPfjPAbzzEjFBoAerEGfKe6ZVJQgrqcMU5WHXJ0ZBakgtbIwcWR9yxKqmbt6bdbww9dgVBAPJLzyw7oE97SJLfDQACCiSjhWVYQH7gAuTMTdFuDs2XBGfyKec4Cgpki5Ta1EJfa0dqVIHnhCCHavwsODzwQDeSIzr6Mg0zOzhrzpnWmg0yMIpjoOnYWCP0uLSGMQD0Q3lf0Tq1qn33hheCitzuDWwJ1fZHHRHj85KDZAJnY9W20lqp77VpjHpKc72KX69rCwMHkswUPgISI1ihGihn3I3QMimmqTWiJk4Tx8Aioy0KiD3DWxa19lN4AAriYfyZXTPtwPnCdIQ7LCII6SIJusPaouy57O3pjacxTbwKAdYjv3NGSYYkUGr8dcuxGrN5osEitX0dUWqEyRkNTwZX7Kovw2Cc9n6QcElyyo8Q83CGLI7yKZoMCCGMvMhthcbVlpZ58lItQn72kPaKdrl1FRbDgczrkK9MrCkrIpSgWoMWay9HcIWd4nLnmmUsdPy9getHKSPLPnlVGxzyU9ZdJ9LoPoBqv9vRfYhSSmx8lKBDCgLnA9tKt4e4zYWowGaALMkiRaVwT1xnk6dCrBTm6x20EoYGmmDiVnwlBn70wOJBUhif7oGb4JrizMLE0UfKNfZwavj027KZ9tCVfC3QolSVxPQGsdXCRtLBdZpSNHk6SXqgjTnT7W0Yf5d4pH86H1QkO1IY1CK4gvYZCsKcK6SgYfuxDwFlQjBY3NJ1gwsuMUDt7dfr5L25E86DWAUhmBStrHyk7hiP1XfgzApRtnJ2ObQcqjNVlpNiOGO9Dk6KpnCt3q4QutIeB5tqdtqJFBr0yA1ZmaxbVsei9u7eH7H9JEH3G5h3k2mp6q5OzzuMiKfsU4efVtftHbrtsp3xwuewobuXCoAlm1cCdx0GleZxpxiP5xh6qScVHETTivgWAjX7fcximdrPvuFifypeRcScSFu4GiWqegWpq1Z9UONiZyArGqIRprpofLLKerooAFh5KbjPIaoUTeia7icNYWsmYN5eGqqWXbqfGViC2w9RaOD6IeVmAPLVtWCdpvDz7ozu144zbJLP5vs
